In [1]:
### @author: Sander Buhling 


#info
# button colors
# ''           = white             = Empty
# 'success'    = 'green'           = Manual input
# 'info'       = 'blue'            = From input grid / fixed
#'warning'     = orange / yellow   = Calculated
#'danger'      = 'red'             = Incorrect

from ipywidgets import widgets, GridspecLayout, Layout
from IPython.display import display
import numpy as np, sys
from datetime import datetime

### Define Button On_Click actions
def on_button_clicked(b):
    if str(toggle_options.value) == 'Clear' : 
        b.description = '-'
        b.button_style= ''
    else : 
        b.description = str(toggle_options.value)
        b.button_style='success'
        print(b.tooltip + 'value:' + b.description)
        #Row:1, Column:3value:1
        #grid[]
    
def on_reset_clicked(b):
    sudoku.description = '-'
    for k in range(3):          # matrix Column
        for l in range(3):       # matrix Row
            for i in range(3):    # matrix Column
                for j in range(3): # matrix Row
                    sudoku[k,l][i,j].description = '-'


### Define all fields
#grid[row][column]               
#grid = [[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],
#        [0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],
#        [0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0]]
grid = [[0,0,4,0,2,0,0,7,0],[0,7,0,0,0,0,6,2,0],[0,0,0,0,8,7,4,3,0],
       [2,0,0,8,0,0,9,0,0],[0,6,0,0,0,0,0,1,0],[0,0,3,0,0,1,0,0,2],
       [0,4,8,7,5,0,0,0,0],[0,5,1,0,0,0,0,9,0],[0,2,0,0,3,0,5,0,0]]

options_text = widgets.HTML(value='<p style="text-align:left"><b>Select Option</b>') 
toggle_options = widgets.ToggleButtons(options=['1', '2', '3', '4', '5', '6', '7', '8', '9', 'Clear'], button_style = 'primary',layout=Layout(width='auto'))
solve_button  = widgets.Button(description='Solve Sudoku', style={'button_color': 'lightgreen'}, layout=Layout(width='100%'), tooltip='Solve Sudoku')

solution_text = "Sudoku Solution: \n" + str(grid[0]) + "\n" + str(grid[1]) + "\n" + str(grid[2]) + "\n" + str(grid[3]) + "\n" + str(grid[4]) + "\n" + str(grid[5]) + "\n" + str(grid[6]) + "\n" + str(grid[7]) + "\n" + str(grid[8])
solution_textbox =widgets.Textarea(value=solution_text, rows=10)
reset_button  = widgets.Button(description='Reset all field',  style={'button_color': 'lightblue'}, layout=Layout(width='100%'), tooltip='Reset all field')
reset_button.on_click(on_reset_clicked)

sudoku = GridspecLayout(3, 3)
sudoku.box_style='danger'
for k in range(3):     # matrix Column
    for l in range(3):     # matrix Row
        sudoku[k,l] = GridspecLayout(3,3, width='auto')
        for i in range(3):     # Column
            for j in range(3): # Row
                if grid[l*3+j][k*3+i] == 0:
                    #sudoku[Matrix Row, Matrix Column][Row, Column]                
                    sudoku[k,l][i,j] = widgets.Button(description='-',
                                                      button_style='', # 'success', 'info', 'warning', 'danger' or ''
                                                      layout=Layout(width='auto'),
                                                      tooltip='Row:' + str(i+1+l*3) + ', Column:' + str(j+1+k*3))
                else:
                    sudoku[k,l][i,j] = widgets.Button(description=str(grid[l*3+j][k*3+i]),#'-',                 
                                                      button_style='info', # 'success', 'info', 'warning', 'danger' or ''
                                                      layout=Layout(width='auto'),
                                                      tooltip='Row:' + str(i+1+l*3) + ', Column:' + str(j+1+k*3))
                sudoku[k,l][i,j].on_click(on_button_clicked)
                
                


### Layout variable. Used for spacing the grid
var1 = int(30) # width of the  3x3 matrix
var2 = int(2)  # width between 3x3 matrix

grid_1 = GridspecLayout(3*var1 + 2*var2 + 1 ,3*var1 + 2*var2 + 1, width='auto')
grid_1[ 0*var1 + 0*var2 : 1*var1 + 0*var2, 0*var1 + 0*var2 : 1*var1 + 0*var2] = sudoku[0,0] #Row1, Column1
grid_1[ 0*var1 + 0*var2 : 1*var1 + 0*var2, 1*var1 + 1*var2 : 2*var1 + 1*var2] = sudoku[1,0] #Row1, Column2
grid_1[ 0*var1 + 0*var2 : 1*var1 + 0*var2, 2*var1 + 2*var2 : 3*var1 + 2*var2] = sudoku[2,0] #Row1, Column3
grid_1[ 1*var1 + 1*var2 : 2*var1 + 1*var2, 0*var1 + 0*var2 : 1*var1 + 0*var2] = sudoku[0,1] #Row2, Column1
grid_1[ 1*var1 + 1*var2 : 2*var1 + 1*var2, 1*var1 + 1*var2 : 2*var1 + 1*var2] = sudoku[1,1] #Row2, Column2
grid_1[ 1*var1 + 1*var2 : 2*var1 + 1*var2, 2*var1 + 2*var2 : 3*var1 + 2*var2] = sudoku[2,1] #Row2, Column3
grid_1[ 2*var1 + 2*var2 : 3*var1 + 2*var2, 0*var1 + 0*var2 : 1*var1 + 0*var2] = sudoku[0,2] #Row2, Column1
grid_1[ 2*var1 + 2*var2 : 3*var1 + 2*var2, 1*var1 + 1*var2 : 2*var1 + 1*var2] = sudoku[1,2] #Row2, Column2
grid_1[ 2*var1 + 2*var2 : 3*var1 + 2*var2, 2*var1 + 2*var2 : 3*var1 + 2*var2] = sudoku[2,2] #Row2, Column3
grid_1.box_style='info'


### Display
layout_header = widgets.VBox([options_text, toggle_options])
layout_body   = widgets.VBox([grid_1])
layout_footer = widgets.HBox([solve_button, solution_textbox, reset_button])
layout_total = widgets.VBox([layout_header, layout_body, layout_footer])
display(layout_total)



In [2]:
#sudoku[2,1]

In [3]:
#l=0 #matrix row
#j=1 #row
#k=2 #matrix column
#i=1 #column
#grid[l*3+j][k*3+i]

In [4]:
#Sudoku Input: 
# [[0 0 4 0 2 0 0 7 0]
# [0 7 0 0 0 0 6 2 0]
# [0 0 0 0 8 7 4 3 0]
# [2 0 0 8 0 0 9 0 0]
# [0 6 0 0 0 0 0 1 0]
# [0 0 3 0 0 1 0 0 2]
# [0 4 8 7 5 0 0 0 0]
# [0 5 1 0 0 0 0 9 0]
# [0 2 0 0 3 0 5 0 0]] 
# Start met oplossen ... 

In [5]:
#text = "12345678"
#text(:3)

In [6]:
###""" @author: Sander.Buhling """
import numpy as np, sys
from datetime import datetime

def possible(y,x,n) :
    global grid, tellerpossible
    tellerpossible += 1
    for i in range(9) : 
        if grid[y][i] == n : return False
    for i in range(9) :
        if grid[i][x] == n : return False
    x0 = (x//3)*3; y0 = (y//3)*3
    for i in range(0,3) : 
        for j in range(0,3) :
            if grid[y0 + i][x0 + j] == n : return False
    return True

def solve() :
    global grid, tellersolve
    if checksolved() : sys.exit()
    tellersolve += 1
    for y in range(9) :
        for x in range(9) :
            if grid[y][x] == 0 :
                for n in range(1,10) :
                    if possible(y,x,n) :
                        grid[y][x] = n
                        solve()
                        grid[y][x] = 0
                return

def checksolved():
    global tellerchecksolved, TellerSolutions, starttime, timeout
    tellerchecksolved += 1
    for y in range(9) :
        for x in range(9) :
            if grid[y][x] == 0 : return False
    elapsed = datetime.now() - starttime
    print('Sudoku Oplossing:', TellerSolutions, '\n', np.matrix(grid), '\n', '\n', 'Opgelost in ', datetime.now() - starttime , '\n',
    "Functie solve: ", tellersolve, '\n',"Functie possible", tellerpossible, '\n', "Functie checksolved", tellerchecksolved)
#    return True# only 1 solution
    
    if not checkmultiplesolutions: return True 
    
    TellerSolutions += 1
    if elapsed.seconds >= timeout: 
        print('\n', 'Time out - Stopping calculations', '\n')
        return True
    if TellerSolutions == maxsolutions : 
        print('\n', 'More than', maxsolutions, '(max) solutions possible - Stopping calculations', '\n')
        return True
    return False
    
grid = [[0,0,4,0,2,0,0,7,0],[0,7,0,0,0,0,6,2,0],[0,0,0,0,8,7,4,3,0],[2,0,0,8,0,0,9,0,0],[0,6,0,0,0,0,0,1,0],[0,0,3,0,0,1,0,0,2],[0,4,8,7,5,0,0,0,0],[0,5,1,0,0,0,0,9,0],[0,2,0,0,3,0,5,0,0]]
#grid = [[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,8,7,4,3,0],[2,0,0,8,0,0,9,0,0],[0,6,0,0,0,0,0,1,0],[0,0,3,0,0,1,0,0,2],[0,4,8,7,5,0,0,0,0],[0,5,1,0,0,0,0,9,0],[0,2,0,0,3,0,5,0,0]]


print('Sudoku Input:', '\n', np.matrix(grid),
      '\n', "Start met oplossen ...", '\n')
starttime = datetime.now()

tellersolve = 0; tellerpossible = 0; tellerchecksolved = 0; TellerSolutions = 1; 

timeout = 10; maxsolutions = 10
checkmultiplesolutions = False

solve()

Sudoku Input: 
 [[0 0 4 0 2 0 0 7 0]
 [0 7 0 0 0 0 6 2 0]
 [0 0 0 0 8 7 4 3 0]
 [2 0 0 8 0 0 9 0 0]
 [0 6 0 0 0 0 0 1 0]
 [0 0 3 0 0 1 0 0 2]
 [0 4 8 7 5 0 0 0 0]
 [0 5 1 0 0 0 0 9 0]
 [0 2 0 0 3 0 5 0 0]] 
 Start met oplossen ... 

Sudoku Oplossing: 1 
 [[1 3 4 9 2 6 8 7 5]
 [8 7 5 3 1 4 6 2 9]
 [6 9 2 5 8 7 4 3 1]
 [2 1 7 8 4 3 9 5 6]
 [4 6 9 2 7 5 3 1 8]
 [5 8 3 6 9 1 7 4 2]
 [9 4 8 7 5 2 1 6 3]
 [3 5 1 4 6 8 2 9 7]
 [7 2 6 1 3 9 5 8 4]] 
 
 Opgelost in  0:00:00.030672 
 Functie solve:  1323 
 Functie possible 11704 
 Functie checksolved 1324


SystemExit: 

To exit: use 'exit', 'quit', or Ctrl-D.


In [75]:
#grid[row][column]
grid

[[1, 3, 2, 4, 6, 5, 7, 8, 9],
 [4, 8, 7, 9, 1, 3, 2, 6, 5],
 [5, 9, 6, 2, 8, 7, 4, 3, 1],
 [2, 1, 4, 8, 7, 6, 9, 5, 3],
 [9, 6, 5, 3, 2, 4, 8, 1, 7],
 [8, 7, 3, 5, 9, 1, 6, 4, 2],
 [3, 4, 8, 7, 5, 9, 1, 2, 6],
 [7, 5, 1, 6, 4, 2, 3, 9, 8],
 [6, 2, 9, 1, 3, 8, 5, 7, 4]]

In [76]:
grid[1][2]

7